# Generated by Django 3.2.1 on 2021-12-03 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet', models.CharField(blank=True, default='self', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 14, 8, 33, 336096), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='btc_equ',
            field=models.CharField(blank=True, default='0.0000000', max_length=200, null=True),
        ),
    ]
