# Generated by Django 3.2.1 on 2021-12-04 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binaryapp', '0003_auto_20211204_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 4, 5, 21, 54, 426236), null=True),
        ),
    ]
