# Generated by Django 3.2.1 on 2021-12-05 09:13

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binaryapp', '0008_auto_20211204_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_back'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_front'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 5, 1, 13, 17, 25337), null=True),
        ),
    ]
